---
# Area
- name: area/github
  color: "72ccf3"
  description: >-
    Changes made to github actions

- name: area/pre-commit
  color: "BC9BE3"
  description: >-
    Changes made to pre-commit hooks

- name: area/dynamo
  color: "7BD7E0"
  description: >-
    Changes made to DynamoDB resources

- name: area/secretsmanager
  color: "7BD7E0"
  description: >-
    Changes made to Secrets Manager resources

- name: area/ssm
  color: "7BD7E0"
  description: >-
    Changes made to SSM resources

- name: area/ec2
  color: "7BD7E0"
  description: >-
    Changes made to EC2 resources

- name: area/s3
  color: "7BD7E0"
  description: >-
    Changes made to Git resources

- name: area/magefiles
  color: "7BD7E0"
  description: >-
    Changes made to Magefiles

- name: area/go-mod-sum
  color: "7BD7E0"
  description: >-
    Changes made to go.mod and go.sum

# Renovate
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"

# Semantic Type
- name: type/digest
  color: "FFEC19"
- name: type/patch
  color: "FFEC19"
- name: type/minor
  color: "FF9800"
- name: type/major
  color: "F6412D"
- name: type/break
  color: "F6412D"

# Uncategorized
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: docs
  color: "F4D1B7"
- name: enhancement
  color: "84b6eb"
- name: question
  description: >-
    Clarification and/or additional information required to move forward
  color: "cc317c"
