---
name: goreleaser
on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    name: Run go releaser
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4
        with:
          go-version: "1.20"

      - name: Fix GOPATH
        run: export PATH=$PATH:$(go env GOPATH)/bin

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@3fa32b8bb5620a2c1afe798654bbad59f9da4906 # v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
