---
name: "Meta Sync labels"
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".github/labels.yaml"]

jobs:
  labels:
    permissions:
      contents: read
      pull-requests: write
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v3.3.0

      - name: Sync Labels
        uses: EndBug/label-sync@v2.3.2
        with:
          config-file: .github/labels.yaml
          delete-other-labels: true
