---
name: Tests
on:
  pull_request:
  push:
    branches: [main]

env:
  AMI: ${{ secrets.AMI }}
  INST_NAME: goawsutilsGHActionTest
  INST_TYPE: t3.micro
  IAM_INSTANCE_PROFILE: AmazonSSMInstanceProfileForInstances
  SEC_GRP_ID: ${{ secrets.SEC_GRP_ID }}
  SUBNET_ID: ${{ secrets.SUBNET_ID }}
  VOLUME_SIZE: 100
  PUB_IP: true
  AWS_DEFAULT_REGION: us-west-1

jobs:
  tests:
    name: Run tests and determine code coverage %
    runs-on: ubuntu-latest
    # Required for OIDC
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Set up git repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: "1.21.5"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          role-session-name: AWSUtilsActionsTest

      - name: Generate the coverage output
        run: |
          bash .hooks/run-go-tests.sh coverage

      - name: Send the coverage output
        uses: shogo82148/actions-goveralls@785c9d68212c91196d3994652647f8721918ba11 # v1
        with:
          path-to-profile: coverage-all.out
