---
name: Tests
on:
  pull_request:
  push:
    branches: [main]

env:
  AMI: ${{ secrets.AMI }}
  INST_NAME: actionsGoInstance
  INST_TYPE: t3.micro
  IAM_INSTANCE_PROFILE: AmazonSSMInstanceProfileForInstances
  SEC_GRP_ID: ${{ secrets.SEC_GRP_ID }}
  SUBNET_ID: ${{ secrets.SUBNET_ID }}
  VOLUME_SIZE: 100
  PUB_IP: true
  AWS_DEFAULT_REGION: us-west-1

jobs:
  tests:
    name: Run tests - includes pre-commit hooks and determining code coverage %
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4
        with:
          go-version: "1.20"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          role-session-name: AWSUtilsActionsTest

      - name: Generate the coverage output
        run: |
          bash .hooks/go-unit-tests.sh coverage

      - name: Send the coverage output
        uses: shogo82148/actions-goveralls@31ee804b8576ae49f6dc3caa22591bc5080e7920 # v1
        with:
          path-to-profile: coverage-all.out

      - name: Report failure
        uses: nashmaniac/create-issue-action@b0c9250ca328a30c2989c7358bc4833f77953af2 # v1.1
        # Only report failures of pushes (PRs are visible through the Checks section) to the default branch
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          title: 🐛 Coverage report failed for ${{ github.sha }}
          token: ${{ secrets.BOT_TOKEN }}
          labels: kind/bug
          body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
